Repository italia/design-scuole-wordpress-theme, pull requests merged in 2024-03, with the labels that each got.

#545 Correzione bug nella memorizzazione htaccess
  inc/admin/options.php
Labels: bug, needs info

#639 Limitazione visualizzazione e accesso documenti albo scaduti e opzione per servizi di richiesta atti
  inc/admin/documento.php
  inc/admin/options.php
  single-documento.php
Labels: enhancement

#635 Circolare senza tipologia "nessuno"
  inc/admin/circolare.php
Labels: enhancement

#625 Amministrazione trasparente fix categories & nested
  inc/vocabolario.php
  page-templates/amministrazione-trasparente.php
  template-parts/search/filters-amministrazione.php
Labels: bug

#560 Possibilità di scegliere più categorie della trasparenza per un singolo documento
  inc/admin/documento.php
Labels: needs info

#633 Visualizzazione dei progetti correlati nelle pagine dei luoghi
  inc/admin/options.php
  inc/utils.php
  single-luogo.php
Labels: enhancement

#649 nascondi la card se il luogo è stato eliminato
  template-parts/luogo/card.php
Labels: enhancement

#650 Corretta errata visualizzazione mappa vuota negli eventi
  template-parts/luogo/card-custom.php
Labels: enhancement

#648 Immagine nei link condivisi
  header.php
Labels: enhancement

#640 Sostituito campo biografia con editor wysiwyg
  inc/admin-js/persona-wysiwyg-bio.js
  inc/admin/persona.php
Labels: enhancement
